name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'  # Only run on the main branch
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }}
